version: "3.5"
services:
  portal:
    image: ${PORTAL_TAG}
    volumes:
      - ./conf/uwsgi/uwsgi.ini:/project/uwsgi.ini
      - /var/www/chameleon/static:/static
      - /var/www/chameleon/media:/media
    env_file:
      - ./conf/portal/.chameleon_env
    command: ["uwsgi", "--ini", "uwsgi.ini"]
    container_name: portal
    restart: always
    logging:
      driver: journald
    networks:
      - app
  mariadb:
    image: mariadb:${DB_TAG}
    volumes: 
      - /var/lib/mysql:/var/lib/mysql
    env_file: 
      - ./conf/portal/.chameleon_env
    container_name: mariadb
    restart: always
    logging:
      driver: journald
    ports:
      - "3306:3006"
    networks: 
      - app
  nginx:
    image: nginx
    volumes:
      - /etc/letsencrypt/live/dev.chameleoncloud.org/fullchain.pem:/etc/ssl/certs/portal.cer
      - /etc/letsencrypt/live/dev.chameleoncloud.org/privkey.pem:/etc/ssl/private/portal.key
      # TODO(jason): we don't yet have DNS records or certs for api.dev.chameleoncloud.org,
      # and the nginx config also assumes a hostname api.chameleoncloud.org, which will
      # not work for dev. For now, just re-use the existing certs so it least nginx starts up.
      - /etc/letsencrypt/live/dev.chameleoncloud.org/fullchain.pem:/etc/ssl/certs/api.portal.cer
      - /etc/letsencrypt/live/dev.chameleoncloud.org/privkey.pem:/etc/ssl/api.chameleoncloud.org.key
      - /var/www/chameleon/static:/static
      - /var/www/chameleon/media:/media
      - /var/www/certbot:/var/www/certbot
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    restart: always
    networks:
      - app
  referenceapi:
    image: ${REFERENCEAPI_TAG}
    container_name: referenceapi
    restart: always
    depends_on:
      - nginx
    networks:
      - app
    volumes:
      - ./conf/referenceapi/reference-repository:/var/db/g5k-api/reference-repository/:ro
  memcached:
    image: memcached:latest
    command: ["-m", "512m"]
    container_name: memcached
    restart: always
    networks:
      - app
  celery:
    image: ${PORTAL_TAG}
    container_name: celery
    command: celery -A chameleon worker -l INFO --concurrency=1 -B
    env_file:
      - ./conf/portal/.chameleon_env
    logging:
      driver: journald
    depends_on:
      - redis
    networks:
      - app

networks:
  app:
    external: true
    name: portal
