version: "3.5"
services:
  portal:
    image: ${PORTAL_TAG}
    volumes:
      - ./conf/uwsgi/uwsgi.ini:/project/uwsgi.ini
      - /var/www/chameleon/static:/var/www/chameleoncloud.org/static/
    env_file:
      - ./conf/portal/.chameleon_env
    command: ["uwsgi", "--ini", "uwsgi.ini"]
    container_name: portal
    restart: always
    networks:
      - app
  nginx:
    image: nginx
    volumes:
      - /etc/ssl/certs/dev.chameleon.bundle.crt:/etc/ssl/certs/portal.cer
      - /etc/ssl/certs/dev.chameleon.tacc.utexas.edu.key:/etc/ssl/private/portal.key
      - /etc/ssl/dhparam.pem:/etc/ssl/dhparam.pem
      - /var/www/chameleon/static:/var/www/chameleoncloud.org/static/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    restart: always
    networks:
      - app
  referenceapi:
    image: ${REFERENCEAPI_TAG}
    container_name: referenceapi
    networks:
      - app
  memcached:
    image: memcached:latest
    command: ["-m", "512m"]
    container_name: memcached
    restart: always
    networks:
      - app
  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - app
  celery:
    image: ${PORTAL_TAG}
    command: celery -A chameleon worker -l info --concurrency=1 -B
    env_file:
      - ./conf/portal/.chameleon_env
    depends_on:
      - redis
    networks:
      - app
networks:
  app:
    external: true
    name: portal
