version: "3.5"
services:
  portal:
    image: ${PORTAL_TAG}
    volumes:
      - ./conf/uwsgi/uwsgi.ini:/project/uwsgi.ini
      - /var/www/chameleon/static:/static
      - /var/www/chameleon/media:/media
    env_file:
      - ./conf/portal/.chameleon_env
    command: ["uwsgi", "--ini", "uwsgi.ini"]
    container_name: portal
    restart: always
    logging:
      driver: journald
    networks:
      - app
  nginx:
    image: nginx
    volumes:
      - /etc/letsencrypt/live/chameleoncloud.org/fullchain.pem:/etc/ssl/certs/portal.cer
      - /etc/letsencrypt/live/chameleoncloud.org/privkey.pem:/etc/ssl/private/portal.key
      - /etc/letsencrypt/live/api.chameleoncloud.org/fullchain.pem:/etc/ssl/certs/api.portal.cer
      - /etc/letsencrypt/live/api.chameleoncloud.org/privkey.pem:/etc/ssl/api.chameleoncloud.org.key
      - /etc/ssl/dhparams.pem:/etc/ssl/dhparam.pem
      - /var/www/chameleon/static:/static
      - /var/www/chameleon/media:/media
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    restart: always
    networks:
      - app
  certbot:
    image: docker.chameleoncloud.org/portal-certbot:latest
    build: 
      dockerfile: ./certbot.Dockerfile
      context: ./conf/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
    container_name: certbot
    restart: always
    depends_on:
      - nginx
  referenceapi:
    image: ${REFERENCEAPI_TAG}
    container_name: referenceapi
    restart: always
    depends_on:
      - nginx
    networks:
      - app
  memcached:
    image: memcached:latest
    command: ["-m", "512m"]
    container_name: memcached
    restart: always
    networks:
      - app
  redis:
    image: "redis:alpine"
    restart: always
    container_name: redis
    networks:
      - app
  celery:
    image: ${PORTAL_TAG}
    container_name: celery
    command: celery -A chameleon worker -l INFO --concurrency=1 -B
    env_file:
      - ./conf/portal/.chameleon_env
    logging:
      driver: journald
    depends_on:
      - redis
    networks:
      - app

networks:
  app:
    external: true
    name: chameleon_default
